// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/CLI deve preferir uma conexão direta (DIRECT_URL), enquanto o app em runtime
    // costuma usar pooled (DATABASE_URL / POSTGRES_URL com pooled=true).
    url: (() => {
      let u =
        process.env["APP_DIRECT_URL"] ??
        process.env["DIRECT_URL"] ??
        process.env["POSTGRES_URL"] ??
        process.env["DATABASE_URL"] ??
        process.env["PRISMA_DATABASE_URL"];
      if (!u || typeof u !== "string" || !u.startsWith("postgres")) {
        throw new Error(
          "URL do banco não configurada. Defina APP_DIRECT_URL (recomendado p/ Vercel+migrations) ou DIRECT_URL/POSTGRES_URL/DATABASE_URL (ex.: postgresql://usuario:senha@localhost:5432/nome_do_banco)"
        );
      }
      // Para migrations, evitar pooled (remove caso tenha vindo de POSTGRES_URL/DATABASE_URL).
      if (u.includes("pooled=true")) {
        u = u.replace(/([?&])pooled=true(&?)/, (_m, sep, tail) => (sep === "?" && tail ? "?" : sep) + (tail ? "" : ""));
        u = u.replace(/[?&]$/, "");
        u = u.replace(/\?&/, "?");
      }
      return u;
    })(),
  },
});
