/**
 * Conteúdo inicial dos Modelos oficiais da Gerência (HTML TipTap + {{variáveis}}).
 * Baseado nos documentos reais em Arquivos/GerenciaAdministrativa/ModelosDocumentos.
 */
export type DocumentTemplateSeed = {
  type: "CONTRATO" | "DISTRATO" | "TERMO_DOACAO";
  title: string;
  contentRich: string;
};

export const DOCUMENT_TEMPLATES_V1: DocumentTemplateSeed[] = [
  {
    type: "CONTRATO",
    title: "Contrato de prestação de serviços (MEI)",
    contentRich: [
      "<h1>CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h1>",
      "<p><strong>Contratante</strong> — {{instituto.nome}}, CNPJ {{instituto.cnpj}}, endereço {{instituto.endereco}}, {{instituto.cidade}}/{{instituto.estado}}, CEP {{instituto.cep}}, neste ato representado(a) por {{instituto.responsavel}}, {{instituto.cargo}}, CPF {{instituto.cpf}}.</p>",
      "<p><strong>Contratado(a)</strong> — {{funcionario.nome}}, RG {{funcionario.rg}}, CPF {{funcionario.cpf}}, residente e domiciliado(a) em {{funcionario.endereco}}.</p>",
      "<p>Pelo presente instrumento particular de Contrato de Prestação de Serviços, as partes acima qualificadas têm entre si justas e avençadas o seguinte.</p>",
      "<h2>CLÁUSULA PRIMEIRA — DO OBJETO</h2>",
      "<p>A CONTRATANTE firma o presente contrato com o(a) CONTRATADO(A), o(a) qual se obriga a prestar à CONTRATANTE serviço profissional na área de <strong>{{funcionario.cargo}}</strong>, sob o regime de prestador de serviços MEI (CNPJ {{funcionario.mei_cnpj}}), assumindo a responsabilidade perante o órgão de fiscalização profissional e outros que lhe exijam.</p>",
      "<h2>CLÁUSULA SEGUNDA — DAS CONDIÇÕES DE EXECUÇÃO DOS SERVIÇOS</h2>",
      "<p>A CONTRATANTE deverá indicar o(a) CONTRATADO(A) conforme sua atividade perante o Conselho Deliberativo e, simultaneamente, o(a) CONTRATADO(A) deverá assinar Declaração – Termo de Responsabilidade, que ficará fazendo parte integrante do presente instrumento.</p>",
      "<h2>CLÁUSULA TERCEIRA — DA REMUNERAÇÃO</h2>",
      "<p>O(A) CONTRATADO(A) é responsável por eventuais retenções de impostos previstas na legislação tributária e previdenciária e receberá, até o 5º dia útil do mês subsequente àquele do serviço efetivamente prestado, a importância de <strong>{{contrato.valor}}</strong>. O pagamento será efetuado por meio de depósito em conta corrente PJ do(a) CONTRATADO(A) ({{funcionario.banco}} / agência {{funcionario.agencia}} / conta {{funcionario.conta}} / PIX {{funcionario.pix}}), mediante apresentação e envio de nota fiscal emitida pelo(a) mesmo(a) por e-mail ({{funcionario.email}}).</p>",
      "<h2>CLÁUSULA QUARTA — DA VIGÊNCIA</h2>",
      "<p>O presente contrato é firmado no período de <strong>{{contrato.inicio}}</strong> a <strong>{{contrato.fim}}</strong>, podendo ser prorrogado de acordo com o desempenho positivo e satisfatório do colaborador junto ao instituto. O(A) contratado(a) cede o direito de imagem para divulgação e promoção do instituto. O presente contrato pode ser rescindido por qualquer das partes; neste caso, a CONTRATANTE pagará ao(à) CONTRATADO(A) o valor correspondente ao tempo de serviço efetivamente prestado, não se aplicando a cláusula sexta.</p>",
      "<h2>CLÁUSULA SEXTA — DA RESCISÃO</h2>",
      "<p>O presente contrato poderá ser rescindido por qualquer uma das partes, mediante notificação prévia à outra por escrito, ressalvada a hipótese de a parte denunciante optar por indenizar a outra do valor correspondente ao da prestação dos serviços referente ao período.</p>",
      "<p><strong>Parágrafo 1º</strong> — O contrato também poderá ser rescindido em caso de violação de quaisquer das cláusulas deste contrato e do regimento do instituto, pela parte prejudicada, mediante denúncia imediata, sem prejuízo de eventual indenização cabível.</p>",
      "<p><strong>Parágrafo 2º</strong> — Qualquer tolerância das partes quanto ao descumprimento das cláusulas do presente contrato constituirá mera liberalidade, não configurando renúncia ou novação do contrato ou de suas cláusulas, que poderão ser exigidas a qualquer tempo.</p>",
      "<h2>CLÁUSULA SÉTIMA — DO REGIME JURÍDICO</h2>",
      "<p>As partes declaram não haver entre si vínculo empregatício, tendo o(a) CONTRATADO(A) plena autonomia na prestação dos serviços, desde que prestados conforme as condições ora pactuadas. O(A) CONTRATADO(A) responde exclusivamente por eventual imprudência, negligência, imperícia ou dolo na execução dos serviços que venham a causar qualquer dano à CONTRATANTE ou a terceiros.</p>",
      "<h2>CLÁUSULA OITAVA — DO FORO DE ELEIÇÃO</h2>",
      "<p>As partes elegem o foro da Comarca da Cidade de {{instituto.cidade}}, para qualquer demanda judicial relativa ao presente contrato, com exclusão de qualquer outro, e por estarem justas e contratadas assinam o presente instrumento em 02 (duas) vias originais de igual teor e forma.</p>",
      "<p>{{instituto.cidade}}, {{contrato.data}}.</p>",
      "<p><br/>_______________________________<br/>{{funcionario.nome}}<br/>Contratado(a)</p>",
      "<p><br/>_______________________________<br/>{{instituto.nome}}<br/>Contratante</p>",
    ].join(""),
  },
  {
    type: "DISTRATO",
    title: "Rescisão de contrato de prestação de serviço",
    contentRich: [
      "<h1>INSTRUMENTO PARTICULAR DE RESCISÃO DE CONTRATO DE PRESTAÇÃO DE SERVIÇO</h1>",
      "<p>De um lado, <strong>{{instituto.nome}}</strong>, inscrito no CNPJ {{instituto.cnpj}}, endereço {{instituto.endereco}}, {{instituto.cidade}}/{{instituto.estado}}, CEP {{instituto.cep}}, neste ato representado(a) por {{instituto.responsavel}}, {{instituto.cargo}}, CPF {{instituto.cpf}}; e de outro lado, <strong>{{funcionario.nome}}</strong>, RG {{funcionario.rg}}, CPF {{funcionario.cpf}}, residente e domiciliado(a) em {{funcionario.endereco}}.</p>",
      "<p>Pelo presente instrumento particular de Rescisão de Contrato de Prestação de Serviços, as partes acima qualificadas têm entre si justas e avençadas o seguinte:</p>",
      "<h2>CLÁUSULA PRIMEIRA — DA RESCISÃO AMIGÁVEL</h2>",
      "<p>As partes celebraram em {{contrato.inicio}} um Contrato de Prestação de Serviços, cujo objeto se tratava de serviço profissional na área de <strong>{{funcionario.cargo}}</strong>.</p>",
      "<p>Pelo presente instrumento particular, resolvem, de mútuo e comum acordo, <strong>RESCINDIR</strong>, amigavelmente, o referido contrato, pelos termos a seguir.</p>",
      "<h2>CLÁUSULA SEGUNDA — DA TOTAL QUITAÇÃO</h2>",
      "<p>As partes transacionaram livremente a rescisão ocorrida e o último dia trabalhado foi <strong>{{contrato.fim}}</strong>. O valor de <strong>{{contrato.valor}}</strong> correspondente ao serviço prestado será quitado mediante a apresentação de nota fiscal do(a) contratado(a) ao contratante, conforme apresentado no contrato de prestação de serviços.</p>",
      "<p><strong>Parágrafo primeiro</strong> — Após a assinatura, as partes, de mútuo e comum acordo, dão entre si total e irrevogável quitação quanto ao objeto contratado, para nada mais reclamarem, a qualquer tempo, uma da outra, quaisquer direitos ou obrigações, seja a que título ou pretexto for, judicial ou extrajudicialmente.</p>",
      "<p>{{instituto.cidade}}, {{contrato.data}}.</p>",
      "<p><br/>_______________________________<br/>{{instituto.nome}}<br/>Contratante</p>",
      "<p><br/>_______________________________<br/>{{funcionario.nome}}<br/>Contratado(a)</p>",
    ].join(""),
  },
  {
    type: "DISTRATO",
    title: "Distrato e encerramento de vínculo de estágio",
    contentRich: [
      "<h1>TERMO DE DISTRATO E ENCERRAMENTO DE VÍNCULO DE ESTÁGIO</h1>",
      "<p><strong>Instituição:</strong> {{instituto.nome}} — CNPJ {{instituto.cnpj}}</p>",
      "<p><strong>Estagiário(a):</strong> {{funcionario.nome}}</p>",
      "<p><strong>CPF:</strong> {{funcionario.cpf}}</p>",
      "<p><strong>Encerramento do vínculo:</strong> {{contrato.fim}}</p>",
      "<p>O {{instituto.nome}}, inscrito no CNPJ {{instituto.cnpj}}, neste ato representado por {{instituto.responsavel}}, {{instituto.cargo}}, e o(a) estagiário(a) {{funcionario.nome}}, CPF {{funcionario.cpf}}, resolvem encerrar, de comum acordo, o vínculo a partir de {{contrato.fim}}.</p>",
      "<h2>CLÁUSULA 1 — DO ENCERRAMENTO</h2>",
      "<p>Fica encerrado o vínculo, extinguindo-se as obrigações contratuais.</p>",
      "<h2>CLÁUSULA 2 — DA DEVOLUÇÃO DE BENS</h2>",
      "<p>O(A) estagiário(a) declara ter devolvido todos os bens institucionais.</p>",
      "<h2>CLÁUSULA 3 — DA QUITAÇÃO</h2>",
      "<p>As partes concedem plena e geral quitação.</p>",
      "<p>{{instituto.cidade}}/{{instituto.estado}}, {{contrato.data}}.</p>",
      "<p><br/>_______________________________<br/>{{instituto.responsavel}}<br/>{{instituto.cargo}} — {{instituto.nome}}</p>",
      "<p><br/>_______________________________<br/>{{funcionario.nome}}<br/>Estagiário(a) — CPF {{funcionario.cpf}}</p>",
    ].join(""),
  },
  {
    type: "TERMO_DOACAO",
    title: "Termo de doação de equipamentos",
    contentRich: [
      "<h1 style=\"text-align:center\">TERMO DE DOAÇÃO DE EQUIPAMENTOS</h1>",
      "<h2>DOADORA</h2>",
      "<p>NOME: {{instituto.nome}}<br/>CNPJ: {{instituto.cnpj}} TEL: {{instituto.telefone}}<br/>ENDEREÇO: {{instituto.endereco}}<br/>MUNICIPIO: {{instituto.cidade}} Estado: {{instituto.estado}} CEP: {{instituto.cep}}<br/>RESPONSÁVEL LEGAL: {{instituto.responsavel}}<br/>CARGO: {{instituto.cargo}} CPF: {{instituto.cpf}}<br/>TEL: {{instituto.telefone}} E-MAIL: {{instituto.email}}</p>",
      "<h2>DONATÁRIA</h2>",
      "<p>Nome: {{donataria.nome}}<br/>Endereço: {{donataria.endereco}}<br/>Responsável: {{donataria.contato}}<br/>Tel.: {{donataria.telefone}}<br/>CNPJ: {{donataria.documento}}<br/>Cidade: {{donataria.cidade}} Estado: {{donataria.estado}}<br/>E-mail: {{donataria.email}}</p>",
      "<h2>OBJETO Anexo I</h2>",
      "<p>O objeto do presente TERMO é a DOAÇÃO, sem nenhum encargo, à DONATÁRIA do(s) seguinte(s) equipamento(s):</p>",
      "<p>Computadores {{doacao.kits}}</p>",
      "<h2>ACORDO</h2>",
      "<p>Pelo presente instrumento particular e na melhor forma de direito, as partes, anteriormente citadas e devidamente qualificadas, resolvem celebrar o presente TERMO DE DOAÇÃO, onde o Instituto Nova Ágora de Cidadania, na qualidade de DOADORA, declara que, de acordo com as diretrizes do Programa Computadores para Inclusão do Governo Federal, do qual é parceira, recondicionou os bens de informática descritos e caracterizados no Anexo I, parte integrante deste TERMO, e que, por autorização expressa da Coordenação de Projetos de Infraestrutura do MCOM, transfere a propriedade desses bens, sem quaisquer encargos, em regime de DOAÇÃO.</p>",
      "<p><strong>São obrigações da Donatária:</strong></p>",
      "<ol type=\"a\">",
      "<li>Utilizar todos os bens doados exclusivamente na realização dos objetivos sociais propostos ao Programa Computadores para Inclusão, e de acordo com as diretrizes de Inclusão Digital normatizadas pelo MCOM;</li>",
      "<li>Adequar a infraestrutura necessária ao funcionamento pleno dos equipamentos, tais como capacidade elétrica, interligação dos computadores em rede, mobiliário, iluminação e ventilação adequada;</li>",
      "<li>Manter os equipamentos conectados à Internet;</li>",
      "<li>Permitir ao público uso livre dos equipamentos, independentemente de cursos ou outras atividades programadas;</li>",
      "<li>Garantir acesso a todo cidadão, ou pelo menos àqueles da comunidade do entorno do espaço;</li>",
      "<li>Realizar a manutenção do local, incluindo limpeza, segurança e custeio;</li>",
      "<li>Manter recursos humanos dedicados a orientar o público no uso dos computadores;</li>",
      "<li>Promover a acessibilidade física e o atendimento a pessoas com necessidades especiais;</li>",
      "<li>Não cobrar da comunidade o acesso à internet;</li>",
      "</ol>",
      "<p>O não cumprimento dessas obrigações volve os bens doados à Entidade Doadora, para que possa doá-los a outra entidade, ficando, assim, autorizada a fiscalização pelo Ministério das Comunicações.</p>",
      "<p>Os bens serão doados com garantia de troca pela DOADORA por um período de três meses, comprometendo-se a DONATÁRIA a arcar com os ônus e riscos decorrentes do transporte desses bens, a partir da efetiva disponibilização dos mesmos. A DONATÁRIA assume inteira responsabilidade por sua guarda, manuseio e manutenção.</p>",
      "<p>{{doacao.local_data}}</p>",
      "<p><br/>_______________________________<br/>{{instituto.nome}}</p>",
      "<p><br/>____________________________________________<br/>{{donataria.nome}}</p>",
    ].join(""),
  },
  {
    type: "TERMO_DOACAO",
    title: "Termo de doação de equipamentos (IGH)",
    contentRich: [
      "<h1 style=\"text-align:center\">TERMO DE DOAÇÃO DE EQUIPAMENTOS</h1>",
      "<h2>DOADORA</h2>",
      "<p>NOME: {{instituto.nome}}<br/>CNPJ: {{instituto.cnpj}}<br/>ENDEREÇO: {{instituto.endereco}}<br/>CIDADE: {{instituto.cidade}} Estado: {{instituto.estado}} CEP: {{instituto.cep}}<br/>RESPONSÁVEL LEGAL: {{instituto.responsavel}}<br/>CARGO: {{instituto.cargo}} CPF: {{instituto.cpf}}<br/>TEL: {{instituto.telefone}} E-MAIL: {{instituto.email}}</p>",
      "<h2>DONATÁRIA</h2>",
      "<p>Instituição: {{donataria.nome}}<br/>CNPJ: {{donataria.documento}}<br/>Endereço: {{donataria.endereco}}<br/>Cidade/Município: {{donataria.cidade}} Estado: {{donataria.estado}}<br/>CEP: {{donataria.cep}} Zona: {{donataria.zona}}<br/>Responsável: {{donataria.contato}}<br/>Telefone: {{donataria.telefone}}<br/>E-mail: {{donataria.email}}</p>",
      "<h2>OBJETO</h2>",
      "<p>O objeto do presente TERMO é a DOAÇÃO, sem nenhum encargo, à DONATÁRIA do(s) seguinte(s) equipamento(s):</p>",
      "<p><strong>Equipamentos / Qtd</strong><br/>{{doacao.itens_lista}}</p>",
      "<p><strong>OBS:</strong> Os termos serão contabilizados somente com preenchimento correto, com os dados devidamente completos e legíveis, sem exceção.</p>",
      "<h2>ACORDO</h2>",
      "<p>Pelo presente instrumento particular e na melhor forma de direito, as partes, anteriormente citadas e devidamente qualificadas, resolvem celebrar o presente TERMO DE DOAÇÃO, onde o CRC IGH, na qualidade de DOADORA, declara que, de acordo com as diretrizes do Programa Computadores para Inclusão do Governo Federal, assinado e publicado no D.O.U., recondicionou os bens de informática descritos e caracterizados no Anexo I, parte integrante deste TERMO, e que, por autorização expressa da Coordenação-Geral de Inclusão Digital do MCOM, transfere a propriedade desses bens, sem quaisquer encargos, em regime de DOAÇÃO.</p>",
      "<p><strong>São obrigações da Donatária:</strong></p>",
      "<ol type=\"a\">",
      "<li>Utilizar todos os bens doados exclusivamente na realização dos objetivos sociais propostos ao Programa Computadores para Inclusão, e de acordo com as diretrizes de Inclusão Digital normatizadas pelo MCOM;</li>",
      "<li>Adequar a infraestrutura necessária ao funcionamento pleno dos equipamentos, tais como capacidade elétrica, interligação dos computadores em rede, mobiliário, iluminação e ventilação adequada;</li>",
      "<li>Manter os equipamentos conectados à Internet;</li>",
      "<li>Permitir ao público uso livre dos equipamentos, independentemente de cursos ou outras atividades programadas;</li>",
      "<li>Garantir acesso a todo cidadão, ou pelo menos àqueles da comunidade do entorno do espaço;</li>",
      "<li>Realizar a manutenção do local, incluindo limpeza, segurança e custeio;</li>",
      "<li>Manter recursos humanos dedicados a orientar o público no uso dos computadores;</li>",
      "<li>Promover a acessibilidade física e o atendimento a pessoas com necessidades especiais;</li>",
      "<li>Não cobrar da comunidade o acesso à internet;</li>",
      "</ol>",
      "<p>O não cumprimento dessas obrigações volve os bens doados à Entidade Doadora, para que possa doá-los a outra entidade, ficando, assim, autorizada a fiscalização pelo Ministério das Comunicações.</p>",
      "<p>{{instituto.cidade}}, {{doacao.data}}.</p>",
      "<p><br/>_______________________________<br/>{{instituto.nome}}</p>",
      "<p><br/>____________________________________________<br/>{{donataria.nome}}</p>",
    ].join(""),
  },
];
