export type MetricQuality = "ok" | "partial" | "unavailable" | "estimated";

export type MetricDefinition = {
  metricId: string;
  name: string;
  description: string;
  formulaVersion: string;
  formula: string;
  numerator: string;
  denominator: string;
  unit: string;
  period: string;
  qualityNotes: string;
  source: string;
  page: string;
  desirable: "up" | "down" | "target";
};

export const FORMULA_VERSION_1A = "1A.0.0";

export const DIRECTOR_METRICS_1A: Record<string, MetricDefinition> = {
  "offer.occupancy.current": {
    metricId: "offer.occupancy.current",
    name: "Ocupação atual",
    description: "Vagas ocupadas (ACTIVE+SUSPENDED) sobre capacidade das turmas do recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "ocupantes ÷ capacidade",
    numerator: "matrículas ACTIVE ∪ SUSPENDED",
    denominator: "soma de capacity das turmas (exclui CANCELADA)",
    unit: "%",
    period: "ciclo / recorte de turmas",
    qualityNotes: "Estado atual; não é ocupação inicial.",
    source: "ClassGroup, Enrollment",
    page: "oferta-territorios",
    desirable: "target",
  },
  "offer.low_occupancy.classes": {
    metricId: "offer.low_occupancy.classes",
    name: "Turmas com ocupação crítica",
    description: "Turmas sem inscritos ou com ocupação atual abaixo de 30%.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(ocupação=0 ∨ ocupação<30%)",
    numerator: "turmas críticas",
    denominator: "—",
    unit: "turmas",
    period: "ciclo",
    qualityNotes: "Agregado operacional.",
    source: "ClassGroup, Enrollment",
    page: "oferta-territorios",
    desirable: "down",
  },
  "offer.waitlist.count": {
    metricId: "offer.waitlist.count",
    name: "Lista de espera",
    description: "Reservas WAITING no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(EnrollmentWaitlist.status=WAITING)",
    numerator: "reservas",
    denominator: "—",
    unit: "pessoas/reservas",
    period: "ciclo",
    qualityNotes: "Pode haver mais de uma reserva por pessoa em turmas distintas.",
    source: "EnrollmentWaitlist",
    page: "oferta-territorios",
    desirable: "target",
  },
  "offer.seat_offer.accept_rate": {
    metricId: "offer.seat_offer.accept_rate",
    name: "Taxa de aceite de ofertas de vaga",
    description: "Ofertas ACCEPTED ÷ ofertas decididas (ACCEPTED+EXPIRED+CANCELLED), excluindo PENDING.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "accepted ÷ (accepted+expired+cancelled)",
    numerator: "ACCEPTED",
    denominator: "ACCEPTED ∪ EXPIRED ∪ CANCELLED",
    unit: "%",
    period: "ciclo",
    qualityNotes: "Indisponível se denominador=0.",
    source: "WaitlistSeatOffer",
    page: "oferta-territorios",
    desirable: "up",
  },
  "acad.pre_enroll.count": {
    metricId: "acad.pre_enroll.count",
    name: "Pré-matrículas",
    description: "Matrículas com isPreEnrollment=true no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(isPreEnrollment)",
    numerator: "pré-matrículas",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Não confundir com confirmadas.",
    source: "Enrollment",
    page: "academico",
    desirable: "target",
  },
  "acad.enroll.confirmed": {
    metricId: "acad.enroll.confirmed",
    name: "Matrículas confirmadas",
    description: "Matrículas com isPreEnrollment=false no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(!isPreEnrollment)",
    numerator: "confirmadas",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Inclui ACTIVE/SUSPENDED/COMPLETED/CANCELLED conforme filtro de status.",
    source: "Enrollment",
    page: "academico",
    desirable: "up",
  },
  "acad.attendance.present_rate": {
    metricId: "acad.attendance.present_rate",
    name: "Frequência (presença)",
    description: "Presenças ÷ oportunidades elegíveis aluno×sessão.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "presenças ÷ oportunidades elegíveis",
    numerator: "SessionAttendance.present=true em sessões elegíveis",
    denominator: "pares (matrícula, sessão LIBERADA ≤ dataAsOf após entrada do aluno)",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "Sessões SCHEDULED passadas geram alerta de qualidade.",
    source: "ClassSession, SessionAttendance, Enrollment",
    page: "academico",
    desirable: "up",
  },
  "acad.attendance.justified_rate": {
    metricId: "acad.attendance.justified_rate",
    name: "Taxa de faltas justificadas",
    description: "Faltas justificadas ÷ oportunidades elegíveis.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "faltas justificadas ÷ oportunidades elegíveis",
    numerator: "present=false com justificativa não vazia",
    denominator: "iguais à presença",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "Justificada permanece no denominador da presença.",
    source: "ClassSession, SessionAttendance",
    page: "academico",
    desirable: "target",
  },
  "acad.attendance.unjustified_rate": {
    metricId: "acad.attendance.unjustified_rate",
    name: "Taxa de faltas não justificadas",
    description: "Faltas sem justificativa ÷ oportunidades elegíveis.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "faltas não justificadas ÷ oportunidades elegíveis",
    numerator: "present=false sem justificativa",
    denominator: "iguais à presença",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "",
    source: "ClassSession, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "acad.attrition.risk.critical_absences": {
    metricId: "acad.attrition.risk.critical_absences",
    name: "Risco crítico por faltas",
    description:
      "Matrículas ACTIVE/SUSPENDED com streak ≥4 faltas consecutivas sem justificativa (limite de cancelamento).",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(vinculados com streak≥CANCEL_LIMIT)",
    numerator: "matrículas em risco",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo / dataAsOf",
    qualityNotes: "Não é evasão confirmada.",
    source: "Enrollment, ClassSession LIBERADA, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "acad.suspension.count": {
    metricId: "acad.suspension.count",
    name: "Matrículas suspensas",
    description: "status=SUSPENDED no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(SUSPENDED)",
    numerator: "suspensos",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Regra operacional: 3 faltas consecutivas s/ justificativa.",
    source: "Enrollment",
    page: "academico",
    desirable: "down",
  },
  "acad.completion.started_rate": {
    metricId: "acad.completion.started_rate",
    name: "Taxa de conclusão (quem iniciou)",
    description: "COMPLETED∩iniciou ÷ iniciou, apenas turmas ENCERRADA.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "completed_started ÷ started",
    numerator: "COMPLETED com ≥1 presença elegível",
    denominator: "matrículas com ≥1 presença elegível em turmas ENCERRADA",
    unit: "%",
    period: "coortes encerradas do ciclo",
    qualityNotes: "Indisponível se não houver coorte encerrada/madura.",
    source: "Enrollment, ClassGroup, SessionAttendance",
    page: "academico",
    desirable: "up",
  },
  "acad.cancel.after_start_untyped": {
    metricId: "acad.cancel.after_start_untyped",
    name: "Cancelamentos após o início — motivo não tipado",
    description: "CANCELLED com ≥1 presença elegível (sem motivo estruturado).",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(CANCELLED ∩ started)",
    numerator: "cancelamentos pós-início",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Qualidade parcial — não é evasão confirmada.",
    source: "Enrollment, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "ben.served_unique": {
    metricId: "ben.served_unique",
    name: "Alunos efetivamente atendidos (únicos)",
    description: "studentId distintos com ≥1 presença elegível no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "COUNT DISTINCT studentId com presença",
    numerator: "pessoas",
    denominator: "—",
    unit: "pessoas",
    period: "ciclo / dataAsOf",
    qualityNotes: "Não usa só data de matrícula.",
    source: "Enrollment, SessionAttendance",
    page: "academico",
    desirable: "up",
  },
};

export function getMetricDefinition(metricId: string): MetricDefinition | undefined {
  return DIRECTOR_METRICS_1A[metricId];
}

export function listMetricsForGuide(): MetricDefinition[] {
  return Object.values(DIRECTOR_METRICS_1A);
}
