export type MetricQuality = "ok" | "partial" | "unavailable" | "estimated";

export type MetricDefinition = {
  metricId: string;
  name: string;
  description: string;
  formulaVersion: string;
  formula: string;
  numerator: string;
  denominator: string;
  unit: string;
  period: string;
  qualityNotes: string;
  source: string;
  page: string;
  desirable: "up" | "down" | "target";
};

export const FORMULA_VERSION_1A = "1A.0.0";
export const FORMULA_VERSION_1B = "1B.0.0";
export const FORMULA_VERSION_1C = "1C.0.0";
export const EXECUTIVE_METHODOLOGY_LABEL = "Metodologia dos indicadores — versão 1.0";

export const DIRECTOR_METRICS_1A: Record<string, MetricDefinition> = {
  "offer.occupancy.current": {
    metricId: "offer.occupancy.current",
    name: "Ocupação atual",
    description: "Vagas ocupadas (ACTIVE+SUSPENDED) sobre capacidade das turmas do recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "ocupantes ÷ capacidade",
    numerator: "matrículas ACTIVE ∪ SUSPENDED",
    denominator: "soma de capacity das turmas (exclui CANCELADA)",
    unit: "%",
    period: "ciclo / recorte de turmas",
    qualityNotes: "Estado atual; não é ocupação inicial.",
    source: "ClassGroup, Enrollment",
    page: "oferta-territorios",
    desirable: "target",
  },
  "offer.low_occupancy.classes": {
    metricId: "offer.low_occupancy.classes",
    name: "Turmas com ocupação crítica",
    description: "Turmas sem inscritos ou com ocupação atual abaixo de 30%.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(ocupação=0 ∨ ocupação<30%)",
    numerator: "turmas críticas",
    denominator: "—",
    unit: "turmas",
    period: "ciclo",
    qualityNotes: "Agregado operacional.",
    source: "ClassGroup, Enrollment",
    page: "oferta-territorios",
    desirable: "down",
  },
  "offer.waitlist.count": {
    metricId: "offer.waitlist.count",
    name: "Lista de espera",
    description: "Reservas WAITING no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(EnrollmentWaitlist.status=WAITING)",
    numerator: "reservas",
    denominator: "—",
    unit: "pessoas/reservas",
    period: "ciclo",
    qualityNotes: "Pode haver mais de uma reserva por pessoa em turmas distintas.",
    source: "EnrollmentWaitlist",
    page: "oferta-territorios",
    desirable: "target",
  },
  "offer.seat_offer.accept_rate": {
    metricId: "offer.seat_offer.accept_rate",
    name: "Taxa de aceite de ofertas de vaga",
    description: "Ofertas ACCEPTED ÷ ofertas decididas (ACCEPTED+EXPIRED+CANCELLED), excluindo PENDING.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "accepted ÷ (accepted+expired+cancelled)",
    numerator: "ACCEPTED",
    denominator: "ACCEPTED ∪ EXPIRED ∪ CANCELLED",
    unit: "%",
    period: "ciclo",
    qualityNotes: "Indisponível se denominador=0.",
    source: "WaitlistSeatOffer",
    page: "oferta-territorios",
    desirable: "up",
  },
  "acad.pre_enroll.count": {
    metricId: "acad.pre_enroll.count",
    name: "Marcação técnica de confirmação no sistema",
    description:
      "Campo interno isPreEnrollment. Não é uma coorte da diretoria: quem não confirma no sistema também assiste às aulas.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(isPreEnrollment)",
    numerator: "registros com marcação",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Não usar como métrica executiva. Todas as matrículas entram na mesma coorte.",
    source: "Enrollment",
    page: "academico",
    desirable: "target",
  },
  "acad.enroll.confirmed": {
    metricId: "acad.enroll.confirmed",
    name: "Matrículas",
    description: "Todas as matrículas do recorte, independentemente da confirmação no sistema.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(Enrollment)",
    numerator: "matrículas",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Inclui ACTIVE/SUSPENDED/COMPLETED/CANCELLED conforme filtro de status.",
    source: "Enrollment",
    page: "academico",
    desirable: "up",
  },
  "acad.attendance.present_rate": {
    metricId: "acad.attendance.present_rate",
    name: "Frequência (presença)",
    description: "Presenças ÷ oportunidades elegíveis aluno×sessão.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "presenças ÷ oportunidades elegíveis",
    numerator: "SessionAttendance.present=true em sessões elegíveis",
    denominator: "pares (matrícula, sessão LIBERADA ≤ dataAsOf após entrada do aluno)",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "Sessões SCHEDULED passadas geram alerta de qualidade.",
    source: "ClassSession, SessionAttendance, Enrollment",
    page: "academico",
    desirable: "up",
  },
  "acad.attendance.justified_rate": {
    metricId: "acad.attendance.justified_rate",
    name: "Taxa de faltas justificadas",
    description: "Faltas justificadas ÷ oportunidades elegíveis.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "faltas justificadas ÷ oportunidades elegíveis",
    numerator: "present=false com justificativa não vazia",
    denominator: "iguais à presença",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "Justificada permanece no denominador da presença.",
    source: "ClassSession, SessionAttendance",
    page: "academico",
    desirable: "target",
  },
  "acad.attendance.unjustified_rate": {
    metricId: "acad.attendance.unjustified_rate",
    name: "Taxa de faltas não justificadas",
    description: "Faltas sem justificativa ÷ oportunidades elegíveis.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "faltas não justificadas ÷ oportunidades elegíveis",
    numerator: "present=false sem justificativa",
    denominator: "iguais à presença",
    unit: "%",
    period: "sessões elegíveis até dataAsOf",
    qualityNotes: "",
    source: "ClassSession, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "acad.attrition.risk.critical_absences": {
    metricId: "acad.attrition.risk.critical_absences",
    name: "Risco crítico por faltas",
    description:
      "Matrículas ACTIVE/SUSPENDED com streak ≥4 faltas consecutivas sem justificativa (limite de cancelamento).",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "Quantidade de matrículas ativas ou suspensas com quatro faltas consecutivas sem justificativa, sem sessão desconhecida entre elas.",
    numerator: "matrículas em risco",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo / dataAsOf",
    qualityNotes: "Não é evasão confirmada.",
    source: "Enrollment, ClassSession LIBERADA, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "acad.suspension.count": {
    metricId: "acad.suspension.count",
    name: "Matrículas suspensas",
    description: "status=SUSPENDED no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(SUSPENDED)",
    numerator: "suspensos",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Alerta: 3 faltas consecutivas sem justificativa → suspensão; 4 → cancelamento.",
    source: "Enrollment",
    page: "academico",
    desirable: "down",
  },
  "acad.completion.started_rate": {
    metricId: "acad.completion.started_rate",
    name: "Taxa de conclusão (quem iniciou)",
    description: "COMPLETED∩iniciou ÷ iniciou, apenas turmas ENCERRADA.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "completed_started ÷ started",
    numerator: "COMPLETED com ≥1 presença elegível",
    denominator: "matrículas com ≥1 presença elegível em turmas ENCERRADA",
    unit: "%",
    period: "coortes encerradas do ciclo",
    qualityNotes: "Indisponível se não houver coorte encerrada/madura.",
    source: "Enrollment, ClassGroup, SessionAttendance",
    page: "academico",
    desirable: "up",
  },
  "acad.cancel.after_start_untyped": {
    metricId: "acad.cancel.after_start_untyped",
    name: "Cancelamentos após o início — motivo não tipado",
    description: "CANCELLED com ≥1 presença elegível (sem motivo estruturado).",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "count(CANCELLED ∩ started)",
    numerator: "cancelamentos pós-início",
    denominator: "—",
    unit: "matrículas",
    period: "ciclo",
    qualityNotes: "Qualidade parcial — não é evasão confirmada.",
    source: "Enrollment, SessionAttendance",
    page: "academico",
    desirable: "down",
  },
  "ben.served_unique": {
    metricId: "ben.served_unique",
    name: "Alunos efetivamente atendidos (únicos)",
    description: "studentId distintos com ≥1 presença elegível no recorte.",
    formulaVersion: FORMULA_VERSION_1A,
    formula: "COUNT DISTINCT studentId com presença",
    numerator: "pessoas",
    denominator: "—",
    unit: "pessoas",
    period: "ciclo / dataAsOf",
    qualityNotes: "Não usa só data de matrícula.",
    source: "Enrollment, SessionAttendance",
    page: "academico",
    desirable: "up",
  },
};

export const DIRECTOR_METRICS_1B: Record<string, MetricDefinition> = {
  "fin.posted.in": {
    metricId: "fin.posted.in",
    name: "Receitas lançadas",
    description: "Soma de ENTRADA com entryDate no período (deletedAt nulo).",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents ENTRADA onde entryDate ∈ período",
    numerator: "centavos lançados",
    denominator: "—",
    unit: "centavos",
    period: "competência ou intervalo (entryDate)",
    qualityNotes: "Não é recebimento. Pago sem paidAt gera qualidade parcial.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
  "fin.posted.out": {
    metricId: "fin.posted.out",
    name: "Despesas lançadas",
    description: "Soma de SAIDA com entryDate no período.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents SAIDA onde entryDate ∈ período",
    numerator: "centavos lançados",
    denominator: "—",
    unit: "centavos",
    period: "competência ou intervalo (entryDate)",
    qualityNotes: "Não é pagamento.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
  "fin.paid.in": {
    metricId: "fin.paid.in",
    name: "Receitas pagas/recebidas",
    description: "ENTRADA PAGO com paidAt no período.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents ENTRADA PAGO onde paidAt ∈ período",
    numerator: "centavos recebidos",
    denominator: "—",
    unit: "centavos",
    period: "competência ou intervalo (paidAt)",
    qualityNotes: "Exclui PAGO sem paidAt do numerador.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "up",
  },
  "fin.paid.out": {
    metricId: "fin.paid.out",
    name: "Despesas pagas",
    description: "SAIDA PAGO com paidAt no período.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents SAIDA PAGO onde paidAt ∈ período",
    numerator: "centavos pagos",
    denominator: "—",
    unit: "centavos",
    period: "competência ou intervalo (paidAt)",
    qualityNotes: "Exclui PAGO sem paidAt.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
  "fin.net.paid": {
    metricId: "fin.net.paid",
    name: "Movimentação líquida (lançamentos pagos)",
    description: "Receitas pagas − despesas pagas no critério paidAt.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "fin.paid.in − fin.paid.out",
    numerator: "diferença em centavos",
    denominator: "—",
    unit: "centavos",
    period: "paidAt",
    qualityNotes: "Não representa saldo ou disponibilidade bancária.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
  "fin.ap": {
    metricId: "fin.ap",
    name: "Lançamentos a pagar em aberto",
    description: "SAIDA em EM_ABERTO ou PENDENTE. Não é conta vencida.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents SAIDA aberta",
    numerator: "centavos",
    denominator: "—",
    unit: "centavos",
    period: "estoque em dataAsOf",
    qualityNotes: "Estoque, não série histórica.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "down",
  },
  "fin.ar": {
    metricId: "fin.ar",
    name: "Lançamentos a receber em aberto",
    description: "ENTRADA em EM_ABERTO ou PENDENTE. Não é inadimplência.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ amountCents ENTRADA aberta",
    numerator: "centavos",
    denominator: "—",
    unit: "centavos",
    period: "estoque em dataAsOf",
    qualityNotes: "Estoque atual.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
  "soc.confirmed_unique": {
    metricId: "soc.confirmed_unique",
    name: "Pessoas únicas com matrícula",
    description: "studentId distintos com matrícula no recorte (todas as matrículas).",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "COUNT DISTINCT studentId",
    numerator: "pessoas",
    denominator: "—",
    unit: "pessoas",
    period: "ciclo opcional + período",
    qualityNotes: "Não é o mesmo que atendido (presença). Não separa pré-matrícula.",
    source: "Enrollment",
    page: "impacto-social",
    desirable: "up",
  },
  "soc.served_unique": {
    metricId: "soc.served_unique",
    name: "Alunos efetivamente atendidos únicos",
    description: "studentId com ≥1 presença elegível no período.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "COUNT DISTINCT studentId com presença",
    numerator: "pessoas",
    denominator: "—",
    unit: "pessoas",
    period: "from–to / ciclo",
    qualityNotes: "Não soma donatárias institucionais.",
    source: "Enrollment, SessionAttendance",
    page: "impacto-social",
    desirable: "up",
  },
  "soc.computers_donated": {
    metricId: "soc.computers_donated",
    name: "Equipamentos doados",
    description: "Soma kitsCount (ou itens) de doações CONFIRMADA no período.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "Σ kitsCount de Donation CONFIRMADA",
    numerator: "equipamentos/kits",
    denominator: "AnnualGoal.computersTarget quando ano",
    unit: "unidades",
    period: "ano / donatedAt",
    qualityNotes: "Comparável à meta de computadores.",
    source: "Donation, AnnualGoal",
    page: "impacto-social",
    desirable: "up",
  },
  "adm.employees.active": {
    metricId: "adm.employees.active",
    name: "Colaboradores ativos",
    description: "Employees status ATIVO, deletedAt nulo.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "count(ATIVO)",
    numerator: "pessoas",
    denominator: "—",
    unit: "pessoas",
    period: "estoque",
    qualityNotes: "Sem lista nominal.",
    source: "Employee",
    page: "administrativo",
    desirable: "target",
  },
  "adm.contracts.expired": {
    metricId: "adm.contracts.expired",
    name: "Contratos com vigência encerrada na data de referência",
    description: "EmployeeContract ATIVO com endDate < dataAsOf.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "count(endDate < dataAsOf)",
    numerator: "contratos",
    denominator: "—",
    unit: "contratos",
    period: "estoque",
    qualityNotes: "Vencimento objetivo.",
    source: "EmployeeContract",
    page: "administrativo",
    desirable: "down",
  },
  "adm.inventory.zero": {
    metricId: "adm.inventory.zero",
    name: "Itens zerados",
    description: "quantityOnHand ≤ 0, ativo.",
    formulaVersion: FORMULA_VERSION_1B,
    formula: "count(qtd≤0)",
    numerator: "itens",
    denominator: "—",
    unit: "itens",
    period: "estoque",
    qualityNotes: "Não é pipeline unitário.",
    source: "InventoryItem",
    page: "administrativo",
    desirable: "down",
  },
};

export const DIRECTOR_METRICS_1C: Record<string, MetricDefinition> = {
  "fin.open.age_91": {
    metricId: "fin.open.age_91",
    name: "Lançamentos em aberto há mais de 90 dias",
    description:
      "Soma em centavos de lançamentos EM_ABERTO/PENDENTE com idadeEmAberto = dataAsOf − entryDate > 90. Não é vencimento: o schema não possui dueDate.",
    formulaVersion: FORMULA_VERSION_1C,
    formula: "Σ amountCents abertos com (dataAsOf − entryDate) > 90 dias",
    numerator: "centavos",
    denominator: "—",
    unit: "centavos",
    period: "estoque em dataAsOf",
    qualityNotes: "Idade do registro em aberto, não atraso.",
    source: "FinancialEntry.entryDate + paymentStatus",
    page: "financeiro",
    desirable: "down",
  },
  "fin.ap": {
    metricId: "fin.ap",
    name: "Lançamentos a pagar em aberto",
    description: "SAIDA em EM_ABERTO ou PENDENTE. Não afirma vencimento.",
    formulaVersion: FORMULA_VERSION_1C,
    formula: "Σ amountCents SAIDA aberta",
    numerator: "centavos",
    denominator: "—",
    unit: "centavos",
    period: "estoque em dataAsOf",
    qualityNotes: "Idade em aberto ≠ atraso. Sem dueDate.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "down",
  },
  "fin.ar": {
    metricId: "fin.ar",
    name: "Lançamentos a receber em aberto",
    description: "ENTRADA em EM_ABERTO ou PENDENTE. Não é inadimplência.",
    formulaVersion: FORMULA_VERSION_1C,
    formula: "Σ amountCents ENTRADA aberta",
    numerator: "centavos",
    denominator: "—",
    unit: "centavos",
    period: "estoque em dataAsOf",
    qualityNotes: "Sem dueDate no schema.",
    source: "FinancialEntry",
    page: "financeiro",
    desirable: "target",
  },
};

export function getMetricDefinition(metricId: string): MetricDefinition | undefined {
  return DIRECTOR_METRICS_1C[metricId] ?? DIRECTOR_METRICS_1B[metricId] ?? DIRECTOR_METRICS_1A[metricId];
}

export function listMetricsForGuide(): MetricDefinition[] {
  const merged = { ...DIRECTOR_METRICS_1A, ...DIRECTOR_METRICS_1B, ...DIRECTOR_METRICS_1C };
  return Object.values(merged);
}
